### ISSUE TITLE
Suggestion: Extend Functionality to Chocobo Saddlebag? 

### ISSUE THREAD

**Issue by gamma-blocker** [MidoriKami/SortaKinda#11]
Possibility, capacity, and interest to update the plugin's functionality to include the Chocobo Saddlebag?

Could allow for the following:
 - Sort Chocobo Saddlebag upon opening
 - Move items from inventory to Chocobo Saddlebag, or vice versa upon opening (depending on selected settings)

Thanks!
Gamma

**Comment by MidoriKami** [comment]
Eventually, but not right now.
