### ISSUE TITLE
Suggestion: Don't sort specific catergory

### ISSUE THREAD

**Issue by vyrnius** [MidoriKami/SortaKinda#12]
Hej!

Thank you very much for your beautiful Plugin! As someone who can't stand a disorganized  Inventory, I particularly appreciate your plugin! :-)

However, I have a suggestion for improvement... could you add an option to disable automatic sorting for specific categories? For instance, I have a category dedicated to handling Materia. I want the plugin to assign such items to their designated slots automatically, but I don't want it to rearrange any Materia that's already in that section.

I believe this feature would be a perfect addition to the plugin, providing users with more flexibility to keep their inventory organized according to their preferences :-)

Thank you for your time and kind regards!

vyrnius

**Comment by MidoriKami** [comment]
Not planned.
