### ISSUE TITLE
Filter items by assigned to any gearset

### ISSUE THREAD

**Issue by noelneedsanap** [MidoriKami/SortaKinda#13]
Requesting a possible feature, being able to filter items by whether they are assigned to a gearset or not.

This would let me select an area at the bottom of each area of my armory for items to collect if they've been replaced or are otherwise not important job gear.

**Comment by MidoriKami** [comment]
Unfortunately SortaKinda does not have access to any data unique to the specific item that you have.

I am not able to read gearset status, repair status, binding status, etc.

I do plan to revisit the core systems of SortaKinda to potentially allow this in the future, but at this time I am not able to reasonably add this feature.
