### ISSUE TITLE
Is it possible to add an option to filter by classes and jobs for equipment?

### ISSUE THREAD

**Issue by VeraKaleid** [MidoriKami/SortaKinda#14]
For example, having a filter that allows only GLA, GNB, PLD.. etc. For these I can do "of Fending" for higher level equipment, but older equipment have more varied naming.

Unrelated, but what does "Use Inclusive Logic" do?

![Screenshot 2023-12-11 134201](https://github.com/MidoriKami/SortaKinda/assets/131595570/b76be072-4b46-4a94-8a99-af4cc5ff5c77)

**Comment by MidoriKami** [comment]
Unfortunately the only methods we have at this time to sort things by job are extremely hacky, and I am not going to add sketchy hacks into SortaKinda.

Inclusive Logic makes it so if an item matches **any** filter it will be allowed, with that disabled an item has to match **all** filters to be allowed.
