### ISSUE TITLE
[Request] Extended text command for adhoc sort

### ISSUE THREAD

**Issue by k0etsu** [MidoriKami/SortaKinda#15]
When "Sort on Inventory Change" is enabled, vendoring/transferring/deleting items can be a slight pain as the auto sort does not occur immediately and can lead to accidents.

Use case would be to manually sort without opening up config window.

**Comment by MidoriKami** [comment]
Please elaborate on what you mean by "`as the auto sort does not occur immediately`"

**Comment by k0etsu** [comment]
Not able to get a video right but essentially when moving items out of the main inventory, there is a slight delay before the sort is performed and by the time it happens I am already trying to move the next and it can lead to the wrong item being selected.

Admittedly, a small concern and I can be more patient when manipulating my inventory but wanted know if this was something that can be implemented with low effort. I confess I'm not too familiar with the KamiLib methods and wasn't sure how to register and then add a single tier command to accomplish this.

**Comment by MidoriKami** [comment]
Ah, well here's a trick when selling things quickly, sell them in reverse order. Start from the bottom right of your inventory and sell moving upwards and to the left.

I have plans to improve the sorting speed, and trigger mechanisms of SortaKinda after the next Dalamud stable release.

**Comment by k0etsu** [comment]
I'll probably try to figure out how to add this myself at some point once I understand the `SingleTierCommandHandler`
