### ISSUE TITLE
Unsorts inventory after logging out

### ISSUE THREAD

**Issue by Devsies** [MidoriKami/SortaKinda#17]
Sorting by name will work during the session I first make the rules, but after logging off and logging back in they will return to unsorted.

**Comment by MidoriKami** [comment]
Unable to reproduce. Please provide more information or a video recording of the issue occuring.

**Comment by Devsies** [comment]
https://imgur.com/a/zmidu3K

It's going from working to not working to just being weird, idk if I'm just doing it incorrectly or not...

First image is me freshly logging back on, rule previously made. Then I show hitting sort, and the filters I used. I then delete the rule and make a new one, same exact filters. It works.
Logged off and on and it stayed, but did it again to check a different one and it went back to messed up.

If you need a video I can try but it will take a while because my steam deck isn't wanting to cooperate with screen recording

**Comment by MidoriKami** [comment]
This might be happening because of the "New Rule" rule you have there, the lower a rule is in the list, the higher the priority of the rule, it might be yielding the other fat cats because "New Rule" is causing a conflict. Can you repeat your tests without "New Rule" being in the list?

**Comment by Devsies** [comment]
Tried deleting new rule (didn't have anything actually assigned to it) and it didn't fix the issue. Also tried just deleting everything and redoing it all, some stuff stays but other things like fat cats, totems just go back to unsorted until I make a new rule for them again. I don't use the same words for anything I'm sorting so not sure if they're somehow conflicting or not.

**Comment by MidoriKami** [comment]
Unfortunately that doesn't help me understand the issue. I'll need a video recording of the occurring and I'll need a copy of all your config files for SortaKinda.
