### ISSUE TITLE
Request: Exclude items or spaces

### ISSUE THREAD

**Issue by Noshei** [MidoriKami/SortaKinda#2]
Would love a way to exclude certain items or spaces from being sorted.

I have about 30-40 items that stay in my bags all the time in specific spots that I wouldn't want sorted at all.  I know I could create a rule for each one, but it would be nice to have a single rule that just says to not sort anything in those specific inventory spaces.

**Comment by MidoriKami** [comment]
I have no plans to add anything like this.

Sounds more to me that you have a set of 30-40 items that you do in fact want sorted into specific spots.
