### ISSUE TITLE
Request: FC chest slot assignment

### ISSUE THREAD

**Issue by alyssadev** [MidoriKami/SortaKinda#24]
Actual sorting of the FC chest isn't in scope due to server requests, but an ingame system for showing slot assignments and maybe highlighting slot mismatches as an overlay would help a great deal with keeping the limited number of slots organised. I was building a spreadsheet with Allagan Tools' csv export, but this functionality might be suitable for SortaKinda.

**Comment by MidoriKami** [comment]
I'm not understanding what you are trying to accomplish.

Is there any way you could attach a couple illustrations of what you would like.

**Comment by alyssadev** [comment]
The request is for an additional tab in SortaKinda for "Company Inventory", perhaps it can require Allagan Tools to populate the slots. It would show the last known state of each of the five 5x10 company chest boxes, allowing the application of filters as with the other inventories.
However, as sorting shared inventories requires server actions, the actual sort behaviour wouldn't be present for the Company Inventory tab. Instead the SortaKinda UI would indicate in some fashion when an item not matching a filter is in a slot.
I hope this picture describes roughly what I'm thinking of
![image](https://github.com/MidoriKami/SortaKinda/assets/63546997/e4909101-353b-4ac4-ac4e-b5376d9e6171)

**Comment by MidoriKami** [comment]
I think that definitely falls out of scope for SortaKinda, would take a rather extensive hack to make it work right.

**Comment by alyssadev** [comment]
All good, thanks for looking into it.
