### ISSUE TITLE
Importing an existing preset does not work

### ISSUE THREAD

**Issue by Rietty** [MidoriKami/SortaKinda#27]
Using the current testing version (v2.0.0.1)

Steps to reproduce: 
1. Create a filter of any type.
2. Export code
3. Try to import code 

Error message:
![image](https://github.com/user-attachments/assets/afc876d1-7ac4-4a18-a38b-990f61fe16db)

Example filter:
```
H4sIAAAAAAAACm2Qy2oCQRBFfyXUuhfTjo5J70JEGFCRyWMjLnqmrtJQTptO+0L897RBQjLJ8p57CqpqcaYnLz6QOV8UlUyGinrIK9RNAZ33i2xQP9h7rXurAYY5cy8jRTO7QTJnONxVO0EiZcs4ktGKHkX8AXxVKqxxxAeZxfKblxGbl9P2H1rZ4KL7KrTKU3eFE+whYycRtxXf0LIP8+Aa/MSvbQyWbS0d6t53v0g6VtDErjg6oYsqbK0Lf0QX0rjzLZlMUWpk6jn9IoVnH+ItXJafaclL41gBAAA=
```

**Comment by MidoriKami** [comment]
Fixed already internally by 5fe47906371e25c28cefeda41ec500da7b216142
