### ISSUE TITLE
Request: Item Description/Effects Filter

### ISSUE THREAD

**Issue by johnkahn** [MidoriKami/SortaKinda#28]
### Description
Would it be possible to include an option similar to Item Name Filter, but for the Description and Effects of an item?

For example, I was wanting to sort all the food I have that gives me a +4% exp buff into a category instead of adding each by name. Could also be useful to group foods by a similar buff (`Crit.*10%` would group all items that give a +10% buff to Critical Hit)

**Comment by MidoriKami** [comment]
That becomes on of these issues: 
![image](https://github.com/user-attachments/assets/a68a3125-f314-4251-b686-c55ee1afe716)

Far too complex/difficult to accomplish.

**Comment by johnkahn** [comment]
lmao thanks for the xkcd, worth a shot at asking 👍🏻
