### ISSUE TITLE
Filter: Market Prohibited / Not Market Prohibited

### ISSUE THREAD

**Issue by Noshei** [MidoriKami/SortaKinda#3]
would be nice to be able to filter by if an item is market prohibited or not.

**Comment by MidoriKami** [comment]
Please explain what you hope to achieve with such a filter

**Comment by Noshei** [comment]
I run a lot of retainer ventures and get a lot of gear from these, having this sort out items that I can sell on the Market Board from items that I can't would be very helpful.

**Comment by MidoriKami** [comment]
![image](https://github.com/MidoriKami/SortaKinda/assets/9083275/54a0f0cb-8869-44ea-809e-c148c2786a42)
I'll do you one better.
