### ISSUE TITLE
[feature request] sort by level

### ISSUE THREAD

**Issue by hhharkness** [MidoriKami/SortaKinda#31]
would it be possible to add an option to sort by level instead of item level?

**Comment by MidoriKami** [comment]
This is likely possible, will investigate as time permits

**Comment by MidoriKami** [comment]
![image](https://github.com/user-attachments/assets/e2d0c0a8-60d2-45c7-a11a-9190757b65f8)
![image](https://github.com/user-attachments/assets/377e94ef-74e9-4314-a00c-5ab97f9b9030)
