### ISSUE TITLE
[bug] main inventory suddenly nor sorting right

### ISSUE THREAD

**Issue by hhharkness** [MidoriKami/SortaKinda#32]
my filters that were working just fine before have suddenly stopped doing what they should, but only in the main inventory - the armoury still works normally. i've checked the settings and the filters still say what they used to and it's not that it doesn't work at all - it does move things around just not according to my filters. can provide exported rules and an example video if needed.

unrelated but i've been meaning to ask, would it be possible to add an option to filter armour by stats? as in "has stat: GP" for example, or possibly "stat: gp>[number]" for more flexibility. would be helpful to separate armour for different jobs that aren't limited in who can equip them! thanks in advance

**Comment by MidoriKami** [comment]
Seek help in the discord, github issues is not for user configuration issues but actual issues with the plugin.
