### ISSUE TITLE
Item Type Filter appears blank

### ISSUE THREAD

**Issue by BobVul** [MidoriKami/SortaKinda#35]
When items are added to the item type filter, the "Nothing filtered" text disappears but the filtered types are not visible/listed. This applies to both existing filters from pre-7.1 and any newly-created filters.

If it matters, my UI scaling is set to 200%.

![image](https://github.com/user-attachments/assets/3245912e-f066-489e-8111-2b8167afe3f9)

It also appears to highlight three items at once when I try to add to the filter, and I can't select anything unless I use the search to narrow it down to one item displayed.

![image](https://github.com/user-attachments/assets/28050788-91fc-4594-b9eb-ac6abff2ef1d)

I'm running 2.1.0.0

**Comment by MidoriKami** [comment]
Please submit dalamud.log and check /xllog ingame for errors (red messages)

**Comment by BobVul** [comment]
Looks like one error that only occurs on initial login. Nothing logged at time of opening the Sorta editor or adding a filter.

![image](https://github.com/user-attachments/assets/beb60372-645d-43ae-a7aa-41ad44dddfc5)

[dalamud.log](https://github.com/user-attachments/files/17877889/dalamud.log)

**Comment by MidoriKami** [comment]
Fixed via combination of:
83fa52016d31f37d85ed357c3f6289fa09820c3e
7d3a575cec323020e11fa8dceeea3a3fef97942c

**Comment by BobVul** [comment]
Type filters now show correctly. Thank you!

The selection window also now works, but it's still a little quirky:

![image](https://github.com/user-attachments/assets/82144b3b-f276-4527-96e4-f3d698ed42e2)

The selection highlight is still two-high, and while it's now possible to add things, it's a bit inaccurate to what I clicked on. In this screenshot, my cursor is on Pugilist's Arm (lower option), but adding actually adds Reaper's Arm (upper option).

This is maybe best shown by selecting below the last option:

![image](https://github.com/user-attachments/assets/20f7e40e-e900-4a5d-ba8f-b64b4adb56fa)

Should I open a new issue for this? It's not that big a deal to work around, but a bit weird.

e: just tested at 100% scaling where this isn't an issue. So it's definitely scaling-related.

**Comment by MidoriKami** [comment]
Please open a new issue yes
