### ISSUE TITLE
Item type selection window does not render correctly when UI scaling is used

### ISSUE THREAD

**Issue by BobVul** [MidoriKami/SortaKinda#36]
Continuation of https://github.com/MidoriKami/SortaKinda/issues/35#issuecomment-2495401137

When UI scaling is used, the item selection menu:

* Has a limited viewport/scrollable area (with empty space at the bottom)
* Highlights multiple items at a time when cursor is moved over them
* Selects a different item from the one the cursor is over

I currently use 200% as default.

A workaround is to temporarily use 100%. Or remember which item gets selected (it's not the one the cursor is directly over). It's a pretty minor issue all things considered.

Some examples:

100%:

![image](https://github.com/user-attachments/assets/4792b54e-290d-4b0b-a2de-4ab2c22398eb)

150%:

![image](https://github.com/user-attachments/assets/5fe340db-f1cb-4bb5-b384-2b3bff2f8126)

200%:

![image](https://github.com/user-attachments/assets/504a7c99-d775-4803-89f6-e4d33e1dd18d)

300%:

![image](https://github.com/user-attachments/assets/6daea82f-7732-4b60-92b1-f176ba52503b)

**Comment by MidoriKami** [comment]
Direct reference to fix code: https://github.com/MidoriKami/KamiLib/commit/83e97a0d766cff554bbd6fe9790633625b9c0a2a

**Comment by BobVul** [comment]
Thank you, all works well now.
