### ISSUE TITLE
[Bug] Entrusting duplicates

### ISSUE THREAD

**Issue by learn2draw** [MidoriKami/SortaKinda#8]
When entrusting duplicates to retainers, if the inventory sorts itselfs the entrusting will get stuck.
This can easily happen when you dump materia into a retainer for example if you have a sortgroup for materia

**Comment by MidoriKami** [comment]
Please attach a video recording of this happening

**Comment by learn2draw** [comment]
@MidoriKami Here's a video attached of the issue 
https://github.com/MidoriKami/SortaKinda/assets/17045310/523f2c4b-421e-4dfe-8510-8e4b91279474

**Comment by MidoriKami** [comment]
What plugin version are you using?
